### ISSUE TITLE
Find configs for mspacman

### ISSUE THREAD

**Issue by k4ntz** [zhixuan-lin/SPACE#3]
First of all, thanks for sharing this amazing work. We are trying to build on top of this work, and I would like to retrain on MsPacman and the other games with personal labeled data.
However, I can't find a proper configuration. I have tried to start from the Space Invaders config. 
Could you explain how we could find these parameters and/or share the one you used for MsPacMan and others ?

**Comment by zhixuan-lin** [comment]
Hi @k4ntz, we don't have a configuration for training only on MsPacman. There is a config file [atari_joint.yaml](https://github.com/zhixuan-lin/SPACE/blob/master/src/configs/atari_joint.yaml) for joint training on 10 games including MsPacman. Maybe you can start from this file for MsPacman and other games.
