### ISSUE TITLE
Object Extraction

### ISSUE THREAD

**Issue by HaQuocHuyPtit** [zhixuan-lin/SPACE#9]
I have a question. How can I extract object after detecting one? Thank you.

**Comment by zhixuan-lin** [comment]
Hello, 

There is no code in this repo that visualizes individual objects, but you can write your own (it is pretty easy). `y_att` [here](https://github.com/zhixuan-lin/SPACE/blob/e1eaf4ad387cd6f79df7fa9682333ea4da2072cc/src/model/space/fg.py#L126) (of shape `(B, G*G, 3, H, W)`) are the extracted (actually reconstructed) objects. You may want to add it to the log [here](https://github.com/zhixuan-lin/SPACE/blob/e1eaf4ad387cd6f79df7fa9682333ea4da2072cc/src/model/space/fg.py#L233) so you get it outside this function. Also, you may want to select non-empty objects from `y_att` with `z_pres` [here](https://github.com/zhixuan-lin/SPACE/blob/e1eaf4ad387cd6f79df7fa9682333ea4da2072cc/src/model/space/fg.py#L237) (shape `(B, G*G, 1)`, you will need to binarize it).
